Audio: IGO NR: Avoid warning about unused variable
This change avoids warning and error about:

sof/src/audio/igo_nr/igo_nr.c:678:20: error: unused variable
'cd' [-Werror,-Wunused-variable]
struct comp_data *cd = module_get_private_data(mod);

Signed-off-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>