module_interface.h: add forward struct comp_dev and timestamp_data
Fixes commit 9cc6454df6d2 ("module_adapter: Extend the module interface
for endpoint devices")

As the endpoint_ops methods use only pointers to these two objects, it's
not necessary to make their entire object structure visible. However a
forward declaration is required to make them known to endpoint_ops users
and fix the following warning:

```
error: 'struct comp_dev' declared inside parameter list will not be
visible outside of this definition or declaration [-Werror]
```

Signed-off-by: Marc Herbert <marc.herbert@intel.com>