IPC4: Add missing header include to alh.h
The use of size_t needs include of stddef.h. Without this
there is build error in copier_hifi.c:

sof/src/include/ipc4/alh.h:70:15: error: unknown type name ‘size_t’

Signed-off-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>