Audio: Smart Amp: Remove unused variable rate
This change fixes warning/error:

sof/src/audio/smart_amp/smart_amp.c:736:11: error: unused
variable 'rate' [-Werror,-Wunused-variable]

Signed-off-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>