Platform: POSIX: Remove unused variable cc
This change avoids error:

sof/src/platform/posix/ipc.c:90:23: error: unused
variable 'cc' [-Werror,-Wunused-variable]

Signed-off-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>