Audio: Smart Amp: Avoid warning about unused
The variable sink_ch is unused. This avoids warning/error:

sof/workspace/sof/src/audio/smart_amp/smart_amp_generic.c:224:6:
error: unused variable 'sink_ch' [-Werror,-Wunused-variable]

Signed-off-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>