audio: force pcm_converter_generic for IPC4 with zephyr
The copier component depends on special pcm conversion
code, which is only implemented in the generic pcm
converter. If we build SOF with IPC4 support with XCC,
the HIFI3 pcm converter is selected automatically, and
causes the issue of
    undefined reference to `pcm_func_vc_count'
    undefined reference to `pcm_func_vc_map'.

This patch forces the use of generic pcm converter
if build SOF with IPC4 and Zephyr.

This patch should be reverted once the HIFI3 pcm converter
counterpart is implemented.

Signed-off-by: Chao Song <chao.song@linux.intel.com>