Platform: POSIX: Avoid warning/error about unused
This change avoid errors:

sof/src/platform/posix/ipc.c:48:7: error: unused variable
'comp_new' [-Werror,-Wunused-variable]

sof/src/platform/posix/ipc.c:49:6: error: unused variable
'comp_idx' [-Werror,-Wunused-variable]

Signed-off-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>