xtensa//cpu.c: give void _WindowOverflow4 a type, fixes -Werror
Fixes this -Werror on tgl platform:

.../xtensa/lib/cpu.c:65:38: error: taking address of expression of
  type 'void' [-Werror]
    void *dyn_vec_start_addr = (void *)(&_WindowOverflow4);

While "void foo;" is syntactically correct, doing anything with it is
illegal in standard C.  Only the tgl platform was affected because it's
the only one with CONFIG_NO_SLAVE_CORE_ROM right now.

Any C type works, I tried a few and when compiling with xtensa-cnl-elf
they all produce the exact same -g0 binaries than the original without
-Werror. I find that the uint8_t[] type doesn't make _WindowOverflow4
look too different from what it is: assembly code.

This is the only change required to compile with the xtensa-cnl-elf
crosstool-ng toolchain documented in the getting started guide.

Note the build with this xtensa-cnl-elf gcc toolchain has NOT been
tested!  The purpose of this commit is purely to add the gcc build to
CI, avoid future gcc bitrot and catch more warnings and bugs.

Fixes  #2516 / commit be083cf35029d0c ("cpu: unpack dynamic vectors")

Signed-off-by: Marc Herbert <marc.herbert@intel.com>