sof/ipc/common.h: add missing #include <ipc/stream.h>
Also move system headers stdbool.h and stdint.h last to avoid them being
accidentally included.

Fixes commit b91e253f65cf2f ("include: sof: debug: Split panic.h into
Zephyr and XTOS-specific headers") that broke `scripts/fuzz.sh` because
it stopped `sof/ipc/common.h` from accidentally getting `ipc/stream.h`
through `panic.h`.

Fixes:

```
src/include/sof/ipc/common.h:126:15: warning: declaration of
 'struct sof_ipc_host_buffer' will not be visible outside of
 this function [-Wvisibility]
                            struct sof_ipc_host_buffer *ring,
                                   ^
```

```
sof/src/ipc/ipc3/host-page-table.c:151:5: error: conflicting types
for 'ipc_process_host_buffer'
int ipc_process_host_buffer(struct ipc *ipc,
    ^

sof/zephyr/../src/include/sof/ipc/common.h:125:5: note: previous
declaration is here:
int ipc_process_host_buffer(struct ipc *ipc,
```

Signed-off-by: Marc Herbert <marc.herbert@intel.com>