sof: dcblock: Fix unaligned pointer value issue
gcc-9 shows the following issue:
error: taking address of packed member of ‘struct sof_abi_hdr’ may
result in an unaligned pointer value [-Werror=address-of-packed-member]
   225 |   request = (int32_t *)cdata->data->data;
       |                        ^~~~~

This commit fixes the issue. The warning was introduced in GCC-9, and
was therefore not raised by previous compiler versions.

Signed-off-by: Sebastiano Carlucci <scarlucci@google.com>