boards: ace30: Enable CONFIG_UAOL for PTL
Starting from Zephyr commit fc2b1b2f3e2 ("drivers: uaol: Do not enable
by default UAOL"), the UAOL (USB Audio Offload Link) driver is no
longer enabled by default. This change cause build failures
with linker errors:
  undefined reference to `__device_dts_ord_110'

This commit enables CONFIG_UAOL=y for PTL

Signed-off-by: Mateusz Junkier <mateusz.junkier@intel.com>