Audio: SRC: Fix build fail when only CONFIG_FORMAT_S16LE is set
The SOF supported formats options are configurable via Kconfig. The
build can fail to this error when the data formats are changed from
default:

sof/src/audio/src/src.c: In function 'src_copy_s32':
sof/src/audio/src/src.c:431:2: error: implicit declaration of function 'audio_stream_copy_s32'; did you mean 'audio_stream_copy_s16'? [-Werror=implicit-function-declaration]
  audio_stream_copy_s32(source, 0, sink, 0, frames * source->channels);
  ^~~~~~~~~~~~~~~~~~~~~
  audio_stream_copy_s16

The common same rate copy function for S16/S24/S32 formats also
simplifies the code.

Signed-off-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>