spinlock: Remove unused variable 'result'
Remove the unused variable 'result' that is causing the build error with GCC 11.4.0.
error: variable 'result' set but not used [-Werror=unused-but-set-variable]

Signed-off-by: SaiSurya Ch <saisurya.chakkaveeravenkatanaga@amd.com>