IPC4: Helper: Avoid warning about unused in ipc4_get_drv()
This change avoids warning/error:

sof/src/ipc/ipc4/helper.c:945:31: error: unused variable
'sof_uuid' [-Werror,-Wunused-variable]

Signed-off-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>