exception: fix ipc timeout issue on bdw
It is a regression issue. L1 interrupt is used by SSP on bdw,
so don't register it as a exception.

Signed-off-by: Rander Wang <rander.wang@linux.intel.com>