kconfig: imx: Disable HIFI3 optimized conversion
With this kconfig option set to y SOF does not build on i.MX platforms,
so we disable this optimized conversion.

The warning below is treated as an error.

sof/src/audio/pcm_converter/pcm_converter_hifi3.c: In function ‘pcm_convert_f_to_s16_lin’:
sof/src/audio/pcm_converter/pcm_converter_hifi3.c:681: warning: implicit declaration of function ‘XT_ROUND_S’

Signed-off-by: Paul Olaru <paul.olaru@nxp.com>