cavs: boot_loader: fix linker error with gcc 10
For GCC build there is known issue with compiler optimization. Different
optimization options cause different issues. For the same reason,
different gcc version might have different problems. This is beyond
human's understanding.

The proper solution is adding missing function to gcc toolchain. But this
is easy workaround. Defined generic memset function in bool_loader.c.

This is error log,
/home/sof/work/xtensa-apl-elf/lib/gcc/xtensa-apl-elf/10.2.0/../../../../xtensa-apl-elf/bin/ld: CMakeFiles/bootloader.dir/__/__/platform/intel/cavs/boot_loader.c.o: in function `strcmp':
/home/sof/work/sof.git/src/platform/intel/cavs/boot_loader.c:206: undefined reference to `memset'
/home/sof/work/xtensa-apl-elf/lib/gcc/xtensa-apl-elf/10.2.0/../../../../xtensa-apl-elf/bin/ld: CMakeFiles/bootloader.dir/__/__/platform/intel/cavs/boot_loader.c.o: in function `bbzero':
/home/sof/work/sof.git/src/platform/intel/cavs/boot_loader.c:79: undefined reference to `memset'

Signed-off-by: Fred Oh <fred.oh@intel.com>