codec_adpater: fix stray errors
Stray errors cause FW build failure when using tigerlake_chrome_waves override config.

./src/audio/codec_adapter/codec/waves.c: In function ‘waves_effect_init’:
./src/audio/codec_adapter/codec/waves.c:338: error: stray ‘\302’ in program
./src/audio/codec_adapter/codec/waves.c:338: error: stray ‘\240’ in program

Fixed by removing invalid characters.

Signed-off-by: CY Kuei <cyk@waves.com>