probe: mtl.toml invaliv probe type
error: invalid type 16error: key 'module' parsing error
probe module type is 10,which is treated hexally

Signed-off-by: Kwasowiec, Fabiola <fabiola.kwasowiec@intel.com>