lib: add memmove function to fix linker error with gcc 10
For GCC build there is known issue with compiler optimization. Different
optimization options cause different issues. For the same reason,
different gcc version might have different problems. This is beyond
human's understanding.

The proper solution is adding missing function to gcc toolchain. But this
is easy workaround. Defined generic memmove function in mux.c.

/home/sof/work/xtensa-apl-elf/lib/gcc/xtensa-apl-elf/10.2.0/../../../../xtensa-apl-elf/bin/ld: CMakeFiles/sof.dir/src/audio/mux/mux.c.o: in function `mux_prepare':
/home/sof/work/sof.git/src/audio/mux/mux.c:657: undefined reference to `memmove'
/home/sof/work/xtensa-apl-elf/lib/gcc/xtensa-apl-elf/10.2.0/../../../../xtensa-apl-elf/bin/ld: CMakeFiles/sof.dir/src/audio/mux/mux.c.o: in function `mux_mix_check':
/home/sof/work/sof.git/src/audio/mux/mux.c:62: undefined reference to `memmove'
collect2: error: ld returned 1 exit status

Signed-off-by: Fred Oh <fred.oh@intel.com>