module_adapter: Fix compilation error with Xtensa toolchain
We get the following error using Xtensa toolchain on i.MX:

src/audio/module_adapter/module_adapter.c:
In function ‘module_adapter_sink_src_prepare’:
src/audio/module_adapter/module_adapter.c:207: error: ‘for’ loop initial declaration used outside C99 mode
src/audio/module_adapter/module_adapter.c:211: error: redefinition of ‘i’
src/audio/module_adapter/module_adapter.c:207: error: previous definition of ‘i’ was here
src/audio/module_adapter/module_adapter.c:211: error: ‘for’ loop initial declaration used outside C99 mode

Fix this by declaring `i` at the top of the function.

Fixes: fa77edf9a47e ("pipeline2.0: change module prepare API to use sink/src.c")
Signed-off-by: Daniel Baluta <daniel.baluta@nxp.com>