zephyr: replace removed IMR_L3_HEAP_SIZE to ace_imr_get_mem_size()
After Zephyr changes in commit af974c30747 replace removed
IMR_L3_HEAP_SIZE to ace_imr_get_mem_size().

This fixes build error:
zephyr/lib/alloc.c:220:27: error: 'IMR_L3_HEAP_SIZE' undeclared
(first use in this function)

Signed-off-by: Mateusz Junkier <mateusz.junkier@intel.com>