trace: Fix compilation error when CONFIG_TRACE not set
Introduce dummy trace functions for when CONFIG_TRACE
is not set to avoid undefined reference to function error.

src/ipc/handler.c.o: In function `ipc_glb_tplg_buffer_new':
src/ipc/handler.c:1094: undefined reference to `trace_on'

Signed-off-by: Daniel Baluta <daniel.baluta@nxp.com>