testbench: remove build warnings when building testbench.
A side effect of the pipeline splitting work means that testbench is
not building. Provide a temporary fix until Zephyr native APIs are used.

/component.c.o   -c /home/lrg/work/sof/sof/src/audio/component.c
/home/lrg/work/sof/sof/src/audio/component.c: In function ‘get_drv’:
/home/lrg/work/sof/sof/src/audio/component.c:41:2: error: ‘flags’ is used uninitialized in this function [-Werror=uninitialized]
   41 |  irq_local_disable(flags);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~
/home/lrg/work/sof/sof/src/audio/component.c: In function ‘comp_register’:
/home/lrg/work/sof/sof/src/audio/component.c:150:2: error: ‘flags’ is used uninitialized in this function [-Werror=uninitialized]
  150 |  irq_local_disable(flags);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~
/home/lrg/work/sof/sof/src/audio/component.c: In function ‘comp_unregister’:
/home/lrg/work/sof/sof/src/audio/component.c:163:2: error: ‘flags’ is used uninitialized in this function [-Werror=uninitialized]
  163 |  irq_local_disable(flags);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

Signed-off-by: Liam Girdwood <liam.r.girdwood@linux.intel.com>