tools: plugin: ipc4: switch to C++17 to build ns module
Compile in C++17 mode to fix:

noise_suppression_interface.cpp:175:14: error: 'clamp' is not a member of 'std'
  175 |     v = std::clamp(v, -1.0f, +1.0f);
      |              ^~~~~
ninja: build stopped: subcommand failed

According to the developer enviroment:
https://docs.openvino.ai/2023.3/system_requirements.html

Required GNU Compiler Collection (GCC) is 7.5 and above
https://gcc.gnu.org/gcc-7/ versions were released from 2017 to 2019

However, -std=c++14 has been the default GNU dialect till GCC 10.x inclusive.

Signed-off-by: Yong Zhi <yong.zhi@intel.com>