trace: Fix build error when spinlock debugging is on
If spinlock debugging is enabled the build currently fails at:

  src/include/sof/spinlock.h:76:31: error: implicit declaration of
    function 'trace_error_atomic'

because trace.h includes spinlock.h before those trace macros get
defined. Fix that by moving all the spinlock-dependent stuff at
the end of the trace.h header file.

Signed-off-by: Dragos Tarcatu <dragos_tarcatu@mentor.com>