ipc3: helper: Fix mixer scenario
With mixer after commit 21ed10abf8a2 ("ipc3: helper: Do not silently
accept unrecognized component type in IPC") we get the following error

dma-trace  src/ipc/ipc3/helper.c:333  ERROR comp_new(): component type not recognized

This happens because now we return an error from comp_specific_builder() with the default
case.

Fix this by adding a case for mixer.

Fixes: 21ed10abf8a2 ("ipc3: helper: Do not silently accept unrecognized component type in IPC")
Signed-off-by: Daniel Baluta <daniel.baluta@nxp.com>