Audio: Module adapter: Fix return value when no prepare operation
The build of testbench for MTL platform simulation causes this build
fail (rebuilt-testbench -p mtl):

src/audio/module_adapter/module/generic.c:213:6:
error: variable 'ret' is used uninitialized whenever 'if'
condition is false [-Werror,-Wsometimes-uninitialized]
        if (md->ops->prepare) {
            ^~~~~~~~~~~~~~~~

src/audio/module_adapter/module/generic.c:236:9:
note: uninitialized use occurs here
        return ret;
               ^~~

Since it's a possibility to have a module without prepare()
operation, the initialize to zero is added to avoid the
return of undefined value.

Reported-by: Marc Herbert <marc.herbert@intel.com>
Signed-off-by: shastry <malladi.sastry@intel.com>
Signed-off-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>