dma-trace.c: fix unsupported mtrace_printf("%s", ...) string specifier
The dictionary does not support character strings.

Fixes commit c11562b00a29 ("dma-trace: Align DMA buffer correctly to fix
dma tracing issues")

Take the opportunity to log the d pointer (which _is_ supported).

Fixes the following error message:

 TIMESTAMP         (us)              DELTA  C# COMPONENT          LOCATION                      CONTENT
error: String printing is not supported
[           2.604167] (           0.000000) c0 dma-trace             src/trace/dma-trace.c:266  ERROR <String @ 0xbe035e60> failed: no DMAC

Signed-off-by: Marc Herbert <marc.herbert@intel.com>