sof: spinlock: Fix placement of spin_try_lock
Enabling CONFIG_DEBUG_LOCKS currently breaks the build for APL as
spin_try_lock is undefined.

src/drivers/intel/cavs/dmic.c:167:8:
error: implicit declaration of function 'spin_try_lock';
did you mean 'arch_try_lock'? [-Werror=implicit-function-declaration]
  ret = spin_try_lock(dai->lock);
        ^~~~~~~~~~~~~

Fix that by making sure spin_try_lock gets defined regardless of
either CONFIG_DEBUG_LOCKS is enabled or not.

Signed-off-by: Dragos Tarcatu <dragos_tarcatu@mentor.com>