panic: add __attribute__((noreturn)) #if __GNUC__
Commit 9e1a2b251a3e ("panic: noreturn attribute for scan build")

 added ((analyzer_noreturn)) but only for clang.

Fixes at least these two -Werr CONFIG_PROBE=y build failures and
probably similar others with a different .config or in the future:

   sof/src/probe/probe.c: In function 'probe_cb_produce':
   sof/src/probe/probe.c:635:11: error: 'valid_bytes' and
   'container_bytes' may be used uninitialized in this function
   [-Werror=maybe-uninitialized]

Build failure reproduced with xtensa-apl-elf-gcc (crosstool-NG
1.23.0.440-3b8c) 7.3.0

Signed-off-by: Marc Herbert <marc.herbert@intel.com>