exception: saving the EPC1 register
It will change in the panic functions so it is needed to save it in exception()

Signed-off-by: Adrian Bonislawski <adrian.bonislawski@linux.intel.com>