src: init: init.c: Remove unused sof_init parameter
This commit fixes compilation error:

"error: initialization of 'int (*)(void)' from incompatible pointer type
'int (*)(const struct device *)' [-Werror=incompatible-pointer-types]"

from SOF CI.

Signed-off-by: Laurentiu Mihalcea <laurentiu.mihalcea@nxp.com>