ipc: Fix compile error
src/include/sof/trace/trace.h:309:32: error: 'type' may be used uninitialized in this function [-Werror=maybe-uninitialized]

This happens when hdr is NULL (even if it may never be at runtime the
compiler still complains) and verbose traces are enabled.

Signed-off-by: Paul Olaru <paul.olaru@nxp.com>