IPC: IPC4: Remove unused function process_dma_index()
Warnings are errors in testbench build. This change avoids error:

sof/src/ipc/ipc4/helper.c:761:19:
error: unused function 'process_dma_index' [-Werror,-Wunused-function]

Signed-off-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>