Audio: Format: Add macro to convert fraction to double
The usage of Q_CONVERT_QTOF() causes build issue with llvm
toolchain when assigned to a double type in ztest code:

error: implicit conversion increases floating-point precision:
'float' to 'double' [-Werror,-Wdouble-promotion]

Since a double is needed to fully match the accuracy of 32 bit
fraction, a new macro Q_CONVERT_QTOD() is added for the purpose.

Signed-off-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>