performance measurements: Fix SOF_TELEMETRY_PERFORMANCE_MEASUREMENTS=n build
Without this change turning the performance measurements off, by setting
CONFIG_SOF_TELEMETRY_PERFORMANCE_MEASUREMENTS=n, causes a number of
"undefined reference to" linker errors.

Signed-off-by: Jyri Sarha <jyri.sarha@linux.intel.com>