host: Fix compilation error with verbose traces enabled
src/audio/host.c: In function 'host_dma_cb':
src/audio/host.c:210:46: error: initialization of
'unsigned int' from 'const struct comp_driver *' makes integer from
pointer without a cast [-Werror=int-conversion]
  comp_cl_dbg(&comp_host, "host_dma_cb() %p", &comp_host);

This happens because our tracing system is limited to integer types
for parameters.

Fixes: a87b9085058492 ("trace: component: use err,info,dbg macros")
Suggested-by: Paul Olaru <paul.olaru@nxp.com>
Signed-off-by: Daniel Baluta <daniel.baluta@nxp.com>