volume: ipc4: Fix compilation due to unused gain_uuid_ldc
Fixes the following compilation failure with gcc:

In file included from src/include/sof/audio/buffer.h:18,
                 from src/include/sof/audio/component.h:19,
                 from src/include/sof/audio/component_ext.h:19,
                 from src/audio/volume/volume.c:18:
src/audio/volume/volume.c:60:29: error: 'gain_uuid_ldc' defined but not used [-Werror=unused-const-variable=]
   60 | DECLARE_SOF_RT_UUID("gain", gain_uuid, 0x61bca9a8, 0x18d0, 0x4a18,
      |                             ^~~~~~~~~
src/include/sof/lib/uuid.h:94:37: note: in definition of macro 'DECLARE_SOF_UUID'
   94 |  static const struct sof_uuid_entry uuid_name ## _ldc = { \
      |                                     ^~~~~~~~~
src/audio/volume/volume.c:60:1: note: in expansion of macro 'DECLARE_SOF_RT_UUID'
   60 | DECLARE_SOF_RT_UUID("gain", gain_uuid, 0x61bca9a8, 0x18d0, 0x4a18,
      | ^~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [CMakeFiles/sof.dir/build.make:534: CMakeFiles/sof.dir/src/audio/volume/volume.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2042: CMakeFiles/sof.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

Signed-off-by: Peter Ujfalusi <peter.ujfalusi@linux.intel.com>